(function () {
const SUCCESS_USE_GOOGLE_SEARCH = false;
const SUCCESS_MAX_SELECTED_CASES = 3;
const SUCCESS_DEFAULT_SEARCH_FIELDS=[{key:'현재직업',weight:6},{key:'이전경력',weight:4},{key:'보유자격교육',weight:5},{key:'준비방법',weight:4},{key:'주요활동',weight:3},{key:'전환유형',weight:3},{key:'추천대상',weight:3},{key:'핵심키워드',weight:5}];
const SUCCESS_DEFAULT_UI={formIntroTitle:'성공사례 DB 기반 상담 분석',formIntroDesc:'입력한 직무, 자격, 경력 키워드를 기준으로 성공사례 DB를 검색하고 상담지원 리포트로 정리합니다.',jobLabel:'성공사례를 찾고 싶은 직업명 *',jobPlaceholder:'예: 소방안전관리, 사회복지, 직업상담, 시설관리',search:'성공사례 검색',reset:'검색 초기화',insightLabel:'참여자에게 연결할 시사점',insightHelp:'1. 참여자의 관심 분야, 이전 경력, 희망 근무 조건<br>2. 자세하게 작성할수록 더 자세한 맞춤 답변 가능',insightPlaceholder:'',generate:'성공사례 분석 리포트 생성',needQuery:'검색 키워드를 입력해주세요.',selectionNotice:'보고 싶은 성공사례를 1개 이상, 최대 3개까지 선택한 뒤 리포트를 생성하세요.',needSelect:'리포트에 포함할 성공사례를 1개 이상 선택해주세요.',maxSelect:'성공사례는 최대 3개까지 선택할 수 있습니다.',missingSelected:'선택한 성공사례를 현재 검색 결과에서 찾을 수 없습니다. 다시 검색한 뒤 선택해주세요.',sourceLabel:'출처',sourceField:'출처문구',previousCareer:'이전 경력',preparation:'준비 방법',currentJob:'현재 직업',certTraining:'자격·교육',activities:'주요 활동',topCases:'대표 성공사례',topCasesDesc:'선택한 성공사례를 기반으로 상담에 활용할 수 있는 준비 방향과 질문을 정리합니다.',prepAnalysis:'준비 내용 및 기간 분석',prepDesc:'사례집의 준비방법과 활동 내용을 바탕으로 상담 참고사항을 정리합니다.',certInfo:'자격증·준비 정보',certFallbackDesc:'사례와 직무 특성을 바탕으로 확인할 준비 정보를 정리합니다.',advice:'상담 활용 코멘트',memo:'상담에 활용할 질문',tableItem:'평가 항목',tableCaseCheck:'사례 기준 확인',tableCounselUse:'상담 활용',certName:'주요 자격·준비',certMethod:'취득 방법',certPeriod:'준비 기간',certOutlook:'급여·전망',reportTitle:'성공사례 기반 재취업 분석 리포트',selectedCount:'건 선택',casebook:'사례집 확인',dbCertMethod:'선택한 성공사례의 자격·교육 항목에서 확인',dbCertPath:'채용공고 요구자격과 대조하고 필요한 교육·시험 일정을 확인',varies:'개인별 상이',variesByJob:'직무·기관별 상이',expandable:'관련 직무 확장 가능',linkedJobs:'연결 직무',commentJobs:'확인된 유사 직무',commentPrep:'공통 준비 흐름',commentBridge:'중장년 사례의 상담에서는 자격 취득 자체보다 기존 경력과 새 직무 요구역량을 연결하는 문장을 만드는 것이 중요합니다.',prepCert:'사례에서 확인된 자격·면허를 채용요건과 대조해 우선순위를 정합니다.',prepProgram:'중장년 지원기관, 직업훈련, 전직지원 프로그램을 공식 이력으로 연결합니다.',prepField:'기존 경력의 관리·운영 경험을 새 직무의 현장 언어로 바꿔 정리합니다.',prepDefault:'유사 사례의 준비방법을 기준으로 자격, 교육, 현장경험, 지원기관 활용 계획을 나눠 실행합니다.',flagCert:'자격증 준비',flagEdu:'교육 수강',flagPractice:'실무 보완',flagResume:'이력서·면접 준비',confirmed:'확인',caseCheck:'사례별 확인 필요',counselCheck:'상담에서 별도 점검',durationNote:'사례집에 준비기간이 명시되지 않은 경우가 많아 평균 산출보다 준비 항목 중심으로 비교합니다.'};
const SUCCESS_ANALYSIS_SCHEMA_FOR_REPAIR={preparationAnalysis:{summary:'',rows:[{item:'',caseCheck:'',typicalPreparation:'',preparationMethod:'',typicalPeriod:'',counselingUse:''}]},certificatePreparationInfo:{summary:'',rows:[{name:'',purpose:'',method:'',typicalPeriod:'',outlook:'',note:''}]},counselingComments:[],counselingQuestions:[]};
function normalizeSuccessGeminiAnalysis(raw={}){const arr=value=>Array.isArray(value)?value.filter(Boolean):[];const table=value=>sanitizeSuccessTableCell(value);const normalized={preparationAnalysis:{summary:String(raw.preparationAnalysis?.summary||''),rows:arr(raw.preparationAnalysis?.rows).map(item=>({item:table(item.item),caseCheck:table(item.caseCheck),typicalPreparation:table(item.typicalPreparation),preparationMethod:table(item.preparationMethod),typicalPeriod:table(item.typicalPeriod),counselingUse:table(item.counselingUse)}))},certificatePreparationInfo:{summary:String(raw.certificatePreparationInfo?.summary||''),rows:arr(raw.certificatePreparationInfo?.rows).map(item=>({name:table(item.name),purpose:table(item.purpose),method:table(item.method),typicalPeriod:table(item.typicalPeriod),outlook:table(item.outlook),note:table(item.note)}))},counselingComments:arr(raw.counselingComments).map(item=>sanitizeSuccessCounselingText(item)).filter(Boolean),counselingQuestions:arr(raw.counselingQuestions).map(item=>sanitizeSuccessCounselingText(item)).filter(Boolean)};const missing=[];if(!normalized.preparationAnalysis.summary||!normalized.preparationAnalysis.rows.length)missing.push('준비 및 기간 분석');if(!normalized.certificatePreparationInfo.summary||!normalized.certificatePreparationInfo.rows.length)missing.push('자격증·준비 정보');if(!normalized.counselingComments.length)missing.push('상담 코멘트');if(!normalized.counselingQuestions.length)missing.push('상담에 활용할 질문');if(missing.length)throw new Error(`Gemini 응답 필수 항목 누락: ${missing.join(', ')}`);return normalized}
function buildSuccessReportData(keyword,matchedCases,participant,insight='',geminiRaw){const items=(matchedCases||[]).filter(Boolean);const rows=items.map(item=>item.case||item).filter(Boolean);if(!rows.length)throw new Error('선택된 성공사례 데이터가 없습니다.');const gemini=normalizeSuccessGeminiAnalysis(geminiRaw);return{keyword,participant,items,rows,generatedAt:new Date().toLocaleString('ko-KR'),keywords:successCommonKeywords(items),prepAnalysis:gemini.preparationAnalysis,certificateInfo:gemini.certificatePreparationInfo,counselingComments:gemini.counselingComments,counselingQuestions:gemini.counselingQuestions}}
function renderSuccessReportFromData(data){const esc=escapeHtml;const prepRows=data.prepAnalysis.rows;const certRows=data.certificateInfo.rows;const topCasesDesc=successUi('topCasesDesc','');return `<div class="success-report"><section class="success-section"><div class="success-section-head"><h2>${successUi('topCases','Representative success cases')}</h2>${topCasesDesc?`<p>${esc(topCasesDesc)}</p>`:''}</div>${successCaseSummaryHtml(data.items.slice(0,5))}</section><section class="success-section"><div class="success-section-head"><h2>${successUi('prepAnalysis','Preparation and duration analysis')}</h2><p>${successUi('prepDesc','Checklist from casebook preparation fields.')}</p></div><div class="success-highlight">${esc(data.prepAnalysis.summary)}</div><table class="success-cert-table"><thead><tr><th>${successUi('tableItem','Item')}</th><th>${successUi('tableCaseCheck','Casebook check')}</th><th>통상 준비 내용</th><th>준비 방법</th><th>통상 준비기간</th><th>${successUi('tableCounselUse','Counseling use')}</th></tr></thead><tbody>${prepRows.map(item=>`<tr><td>${esc(item.item||'-')}</td><td>${esc(item.caseCheck||'-')}</td><td>${esc(item.typicalPreparation||'-')}</td><td>${esc(item.preparationMethod||'-')}</td><td>${esc(item.typicalPeriod||'-')}</td><td>${esc(item.counselingUse||'-')}</td></tr>`).join('')}</tbody></table></section><section class="success-section"><div class="success-section-head"><h2>${successUi('certInfo','Certificate / preparation info')}</h2><p>${successUi('certFallbackDesc','Fallback guidance area.')}</p></div><div class="success-highlight">${esc(data.certificateInfo.summary)}</div><table class="success-cert-table"><thead><tr><th>${successUi('certName','Name')}</th><th>직무 연결 이유</th><th>${successUi('certMethod','Method')}</th><th>${successUi('certPeriod','Period')}</th><th>${successUi('certOutlook','Salary / outlook')}</th><th>확인 사항</th></tr></thead><tbody>${certRows.map(item=>`<tr><td>${esc(item.name||'-')}</td><td>${esc(item.purpose||'-')}</td><td>${esc(item.method||'-')}</td><td>${esc(item.typicalPeriod||'-')}</td><td>${esc(item.outlook||'-')}</td><td>${esc(item.note||'-')}</td></tr>`).join('')}</tbody></table></section><section class="success-section"><div class="success-section-head"><h2>${successUi('advice','Counseling comments')}</h2><p></p></div><div class="success-advice-box">${data.counselingComments.slice(0,6).map(text=>`<p>${esc(text).replaceAll('\n','<br>')}</p>`).join('')}</div></section><section class="success-section"><div class="success-section-head"><h2>${successUi('memo','Counseling questions')}</h2><p></p></div><ul class="success-question-list">${data.counselingQuestions.slice(0,10).map(text=>`<li>${esc(text)}</li>`).join('')}</ul></section></div>`}

function normalizeSuccessText(text){return String(text||'').toLowerCase().replace(/[()[\]{}·ㆍ,./\\|:;'"‘’“”\-+_]/g,' ').replace(/\s+/g,' ').trim()}
function compactSuccessText(text){return normalizeSuccessText(text).replace(/\s+/g,'')}
function successTokens(text){return normalizeSuccessText(text).split(' ').filter(t=>t.length>=2)}
function addSuccessTerm(terms,term){const value=normalizeSuccessText(term);if(value)terms.add(value);const compact=compactSuccessText(term);if(compact&&compact!==value)terms.add(compact)}
function successUi(key,fallback=''){const assist=successSearchAssist();return assist.ui&&assist.ui[key]?assist.ui[key]:(SUCCESS_DEFAULT_UI[key]||fallback)}
function getSuccessQueryTerms(query){const terms=new Set();successTokens(query).forEach(t=>addSuccessTerm(terms,t));addSuccessTerm(terms,query);Object.entries(successRelatedKeywordMap()).forEach(([base,aliases])=>{const safeAliases=Array.isArray(aliases)?aliases:[];const needles=[normalizeSuccessText(base),...safeAliases.map(normalizeSuccessText)].filter(Boolean);const compactNeedles=[compactSuccessText(base),...safeAliases.map(compactSuccessText)].filter(Boolean);const queryCompact=compactSuccessText(query);const matched=compactNeedles.some(v=>queryCompact.includes(v)||v.includes(queryCompact))||successTokens(query).some(token=>needles.some(v=>v.includes(token)||token.includes(v)));if(matched){addSuccessTerm(terms,base);safeAliases.forEach(a=>addSuccessTerm(terms,a))}});return [...terms].filter(t=>t.length>=2)}
function successSearchAssist(){return typeof SUCCESS_CASE_SEARCH_ASSIST==='object'&&SUCCESS_CASE_SEARCH_ASSIST?SUCCESS_CASE_SEARCH_ASSIST:{}}
function successSearchFields(){const assist=successSearchAssist();if(Array.isArray(assist.searchFields)&&assist.searchFields.length)return assist.searchFields;if(typeof SUCCESS_SEARCH_FIELDS==='object'&&Array.isArray(SUCCESS_SEARCH_FIELDS))return SUCCESS_SEARCH_FIELDS;return SUCCESS_DEFAULT_SEARCH_FIELDS}
function successFieldKey(i){return (successSearchFields()[i]||{}).key||''}
function successRelatedKeywordMap(){const legacy=typeof SUCCESS_SIMILAR_KEYWORDS==='object'&&SUCCESS_SIMILAR_KEYWORDS?SUCCESS_SIMILAR_KEYWORDS:{};const assist=successSearchAssist();return {...legacy,...(assist.relatedKeywords||{})}}
function successResultKey(item,index){return String(item?.id||`result-${index}`)}
function successMaxSelectMessage(){return successUi('maxSelect','성공사례는 최대 3개까지 선택할 수 있습니다.')}
function sanitizeSuccessCounselingText(value){return String(value||'').replace(/[가-힣A-Za-z][*＊]{1,}/g,'해당 사례').replace(/[*＊]{2,}/g,'').replace(/\s{2,}/g,' ').replace(/\(\s*\)/g,'').trim()}
function sanitizeSuccessTableCell(value){return String(value||'').trim().replace(/\s+/g,' ').replace(/(해야\s*합니다|하여야\s*합니다)$/,'필요').replace(/(확인해야\s*합니다|확인하여야\s*합니다)$/,'확인 필요').replace(/(권장됩니다|추천됩니다)$/,'권장').replace(/(필요합니다|요구됩니다)$/,'필요').replace(/(가능합니다)$/,'가능').replace(/(입니다|합니다|됩니다|하십시오|하세요)$/,'').replace(/[.。]$/,'').trim()}
function successExtraValue(row,idx){const keys=Object.keys(row||{});return row[keys[idx]]||''}
function successSourceText(row){const field=successUi('sourceField','');return (field&&row&&row[field])||successExtraValue(row,18)||''}
function successFieldScore(value,terms,weight){const text=normalizeSuccessText(value);const compact=compactSuccessText(value);if(!text)return {score:0,terms:[]};let score=0;const matched=[];terms.forEach(term=>{const norm=normalizeSuccessText(term);const c=compactSuccessText(term);if(!norm||!c)return;if(text.includes(norm)||compact.includes(c)){score+=weight;matched.push(term)}else if(norm.length>=3&&text.split(/[\s,./()]+/).some(token=>token&&token.includes(norm))){score+=Math.max(1,Math.floor(weight/2));matched.push(term)}});return {score,terms:matched}}
function successScoreCase(row,query){const terms=getSuccessQueryTerms(query);if(!terms.length)return {score:0,matchedTerms:[],matchedFields:[]};let score=0;const matchedTerms=new Set();const matchedFields=[];successSearchFields().forEach(field=>{const result=successFieldScore(row[field.key],terms,field.weight||1);if(result.score){score+=result.score;matchedFields.push(field.key);result.terms.forEach(t=>matchedTerms.add(t))}});const cq=compactSuccessText(query);const current=compactSuccessText(row[successFieldKey(0)]);if(cq&&current){if(cq===current)score+=30;else if(current.includes(cq)||cq.includes(current))score+=18}const keyword=compactSuccessText(row[successFieldKey(7)]);if(cq&&keyword.includes(cq))score+=12;return {score:Math.min(100,Math.round(score)),matchedTerms:[...matchedTerms],matchedFields:[...new Set(matchedFields)]}}
async function findSuccessCasesFromApi(query,limit=12){const response=await fetch(`/api/success-cases/search?q=${encodeURIComponent(query)}&limit=${encodeURIComponent(limit)}`,{headers:typeof authHeaders==='function'?authHeaders():{},cache:'no-store'});const data=await response.json().catch(()=>null);if(!response.ok)throw new Error(data?.error?.message||'성공사례 DB 검색에 실패했습니다.');return Array.isArray(data?.cases)?data.cases.filter(item=>item&&item.case):[]}
async function findSuccessCasesWithFallback(query,limit=12){const apiResults=await findSuccessCasesFromApi(query,limit);state.successCaseSearchSource='server';return apiResults}
function successSelectedCaseIds(){if(Array.isArray(state.selectedSuccessCaseIds))return state.selectedSuccessCaseIds;return state.selectedSuccessCaseId?[state.selectedSuccessCaseId]:[]}
function collectSelectedSuccessCaseIds(){const checked=[...document.querySelectorAll('input[name="successCaseSelect"]:checked')].map(el=>el.value).filter(Boolean);const selected=checked.length||document.getElementById('successCaseResults')?checked:successSelectedCaseIds();return selected.slice(0,SUCCESS_MAX_SELECTED_CASES)}
function toggleSuccessCaseSelection(id,checked){const ids=new Set(successSelectedCaseIds());if(checked&&ids.size>=SUCCESS_MAX_SELECTED_CASES&&!ids.has(id)){toast(successMaxSelectMessage());[...document.querySelectorAll('input[name="successCaseSelect"]')].forEach(el=>{if(el.value===id)el.checked=false});return}if(checked)ids.add(id);else ids.delete(id);state.selectedSuccessCaseIds=[...ids].slice(0,SUCCESS_MAX_SELECTED_CASES);state.selectedSuccessCaseId=state.selectedSuccessCaseIds[0]||null;const hidden=document.getElementById('successSelectedCaseId');if(hidden)hidden.value=state.selectedSuccessCaseIds.join(',');render()}
async function searchSuccessCases(){const query=val('successJobKeyword');if(!query){toast(successUi('needQuery','Search keyword is required.'));return}const results=await findSuccessCasesWithFallback(query,12);state.successQuery=query;state.successResults=results;state.selectedSuccessCaseIds=results[0]?[successResultKey(results[0],0)]:[];state.selectedSuccessCaseId=state.selectedSuccessCaseIds[0]||null;state.successInsight=val('successInsight');render();toast(results.length?`${results.length} matched cases found.`:'No matched cases found.')}
function chooseSuccessCase(id){toggleSuccessCaseSelection(id,!successSelectedCaseIds().includes(id));render()}
function resetSuccessCaseSearch(){state.successQuery='';state.successResults=[];state.selectedSuccessCaseId=null;state.selectedSuccessCaseIds=[];state.successCaseSearchSource='';state.successInsight='';render()}
function successCaseResultHtml(){const results=state.successResults||[];const selectedIds=successSelectedCaseIds();const maxReached=selectedIds.length>=SUCCESS_MAX_SELECTED_CASES;if(!results.length)return '';return `<div class="notice">${successUi('selectionNotice','Select 1 to 3 success cases.')}</div><div class="success-search-results">${results.map((item,index)=>{const row=item.case;const id=successResultKey(item,index);const selected=selectedIds.includes(id);const disabled=maxReached&&!selected?'disabled':'';return `<label class="success-result-card ${selected?'selected':''}"><input type="checkbox" name="successCaseSelect" value="${escapeHtml(id)}" ${selected?'checked':''} ${disabled} onchange="toggleSuccessCaseSelection('${escapeHtml(id)}',this.checked)"><strong>${escapeHtml(row[successFieldKey(0)])}</strong><span>${escapeHtml(row[successFieldKey(1)])}</span><small>${successUi('sourceLabel','Source')}: ${escapeHtml(successSourceText(row)||'-')}</small></label>`}).join('')}</div>`}
function successFieldRows(row,keys){return keys.map(key=>`<p><strong>${escapeHtml(key)}:</strong> ${escapeHtml(row[key]||'-')}</p>`).join('')}
function successRecommendedPrep(items){const rows=(items||[]).map(item=>item.case||item);const prep=[];if(rows.some(row=>String(row[successFieldKey(2)]||'').trim()))prep.push(successUi('prepCert','Review certificates and licenses found in the casebook.'));if(rows.some(row=>String(row[successFieldKey(3)]||'').trim()))prep.push(successUi('prepProgram','Use public employment, training, and transition support programs as execution steps.'));if(rows.some(row=>String(row[successFieldKey(4)]||'').trim()))prep.push(successUi('prepField','Translate prior management and field activity into job-ready resume language.'));if(!prep.length)prep.push(successUi('prepDefault','Split preparation into certificate, training, field practice, and public support tasks.'));return prep.slice(0,5)}
function successCommonKeywords(items){const counts={};(items||[]).forEach(item=>String((item.case||item)[successFieldKey(7)]||'').split(',').map(v=>v.trim()).filter(Boolean).forEach(v=>{counts[v]=(counts[v]||0)+1}));return Object.entries(counts).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0],'ko')).map(x=>x[0]).slice(0,8)}
function successCaseSummaryHtml(items){return `<div class="success-case-grid">${(items||[]).slice(0,5).map(item=>successCaseCardHtml(item.case||item)).join('')}</div>`}
function successSplitValues(value){return String(value||'').split(/[,\/]| and | or |\n/).map(v=>v.replace(/["'()]/g,'').trim()).filter(Boolean)}
function successCountEntries(rows,key){const counts={};rows.forEach(row=>successSplitValues(row[key]).forEach(v=>{counts[v]=(counts[v]||0)+1}));return Object.entries(counts).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0],'ko'))}
function successTopText(rows,key,empty='-'){const entries=successCountEntries(rows,key);return entries.length?entries.slice(0,3).map(([name,count])=>`${name} (${count})`).join(', '):empty}
function successPrepFlags(rows){return [{label:successUi('flagCert','Certificate preparation'),value:rows.some(row=>String(row[successFieldKey(2)]||'').trim())?successUi('confirmed','Confirmed'):successUi('caseCheck','Check by case')},{label:successUi('flagEdu','Training participation'),value:rows.some(row=>String(row[successFieldKey(3)]||'').trim())?successUi('confirmed','Confirmed'):successUi('caseCheck','Check by case')},{label:successUi('flagPractice','Practical supplement'),value:rows.some(row=>String(row[successFieldKey(4)]||'').trim())?successUi('confirmed','Confirmed'):successUi('caseCheck','Check by case')},{label:successUi('flagResume','Resume/interview'),value:successUi('counselCheck','Check in counseling')}]}
function successDurationSummary(rows){return successUi('durationNote','Many cases do not specify preparation duration, so compare preparation items first.')}
function successCertGuideRows(keyword,rows){const guide=successSearchAssist().certInfo||{};const queryTerms=getSuccessQueryTerms(keyword).map(compactSuccessText);const fromGuide=Object.entries(guide).filter(([key])=>queryTerms.some(t=>compactSuccessText(key).includes(t)||t.includes(compactSuccessText(key)))).flatMap(([,items])=>items);const dbCerts=successCountEntries(rows,successFieldKey(2)).slice(0,4).map(([name])=>({name,difficulty:successUi('casebook','Casebook'),method:successUi('dbCertMethod','Found in SUCCESS_CASE_DB certificate/training field'),path:successUi('dbCertPath','Compare with job posting requirements and check training schedules'),period:successUi('varies','Varies'),salary:successUi('variesByJob','Varies by job'),outlook:successUi('expandable','Expandable to related jobs')}));const seen=new Set();return [...fromGuide,...dbCerts].filter(item=>{const key=compactSuccessText(item.name);if(!key||seen.has(key))return false;seen.add(key);return true}).slice(0,6)}
function successPatternSentences(rows){const transitions=successCountEntries(rows,successFieldKey(5)).slice(0,3);const jobs=successCountEntries(rows,successFieldKey(0)).slice(0,3);const prep=successRecommendedPrep(rows);const sentences=[];if(transitions.length)sentences.push(`${transitions.map(([n,c])=>`${n} ${c}`).join(', ')}`);if(jobs.length)sentences.push(`${successUi('linkedJobs','Linked jobs')}: ${jobs.map(([n])=>n).join(', ')}`);if(prep.length)sentences.push(prep[0]);return sentences}
function successCounselingComments(rows,keyword,insight){const jobs=successTopText(rows,successFieldKey(0),'-');const prep=successTopText(rows,successFieldKey(3),'-');const comments=[`${successUi('commentJobs','Matched jobs')}: ${jobs}`,`${successUi('commentPrep','Preparation pattern')}: ${prep}`,successUi('commentBridge','Bridge prior career assets with new job requirements before focusing only on certificates.')];if(insight)comments.unshift(insight);return comments.slice(0,5)}
function successCaseCardHtml(row){return `<article class="success-case-card"><h3>${escapeHtml(row[successFieldKey(0)])}</h3><p class="small"><strong>${successUi('sourceLabel','Source')}:</strong> ${escapeHtml(successSourceText(row)||'-')}</p><div class="success-timeline"><div><b>${successUi('previousCareer','Previous career')}</b><span>${escapeHtml(row[successFieldKey(1)]||'-')}</span></div><div><b>${successUi('preparation','Preparation')}</b><span>${escapeHtml(row[successFieldKey(3)]||'-')}</span></div><div><b>${successUi('currentJob','Current job')}</b><span>${escapeHtml(row[successFieldKey(0)]||'-')}</span></div></div><dl class="success-mini-list"><dt>${successUi('certTraining','Certificate/training')}</dt><dd>${escapeHtml(row[successFieldKey(2)]||'-')}</dd><dt>${successUi('activities','Activities')}</dt><dd>${escapeHtml(row[successFieldKey(4)]||'-')}</dd></dl></article>`}
function successModuleForm(){const p=getParticipant();if(!p)return `<div class="empty">참여자를 먼저 등록해야 리포트를 생성할 수 있습니다.</div>`;const insightHelp=escapeHtml(successUi('insightHelp','참여자의 이전 경력, 자격 보유 현황, 희망 근무조건, 보완할 준비 등을 작성해주세요. 자세하게 작성할수록 더 자세한 내담자 맞춤 답변이 가능합니다.')).replaceAll('&lt;br&gt;','<br>');return `<div class="job-api-box"><strong>${successUi('formIntroTitle','Public casebook success analysis')}</strong><br>${successUi('formIntroDesc','Searches SUCCESS_CASE_DB and builds a counselor report.')}</div><div class="field"><label>${successUi('jobLabel','Job keyword *')}</label><input id="successJobKeyword" value="${escapeHtml(state.successQuery||p.target||'')}" placeholder="${successUi('jobPlaceholder','ex: safety, counseling, welfare')}" onkeydown="if(event.key==='Enter'){event.preventDefault();searchSuccessCases()}"></div><input type="hidden" id="successSelectedCaseId" value="${escapeHtml(state.selectedSuccessCaseId||'')}"><div class="actions"><button class="btn full" onclick="searchSuccessCases()">${successUi('search','Search cases')}</button><button class="btn secondary full" onclick="resetSuccessCaseSearch()">${successUi('reset','Reset')}</button></div><div id="successCaseResults" style="margin-top:14px">${successCaseResultHtml()}</div><div class="field"><label>${successUi('insightLabel','Counselor insight')}</label><div class="small">${insightHelp}</div><textarea id="successInsight" placeholder="${successUi('insightPlaceholder','')}">${escapeHtml(state.successInsight||'')}</textarea></div><button id="successGenerateButton" class="btn full" onclick="generateSuccessReportWithGemini()">${successUi('generate','Generate counselor report')}</button>`}
function successGeminiError(err){const status=err?.status?'HTTP '+err.status+': ':'';const message=String(err?.apiMessage||err?.message||'알 수 없는 오류');if(err?.isGeminiRateLimit)return GEMINI_RATE_LIMIT_ERROR_MESSAGE;if(err?.isGeminiTemporaryFailure)return 'Gemini API 일시 장애: '+message;if(err?.isNetworkError||err instanceof TypeError)return 'Gemini API 네트워크 오류: '+message;return status?'Gemini API 오류: '+status+message:message}
async function generateSuccessReportWithGemini(){const p=getParticipant();if(!p){toast('내담자 분석 정보를 찾을 수 없습니다.');return}const query=val('successJobKeyword');if(!query){toast(successUi('needQuery','Search keyword is required.'));return}const btn=document.getElementById('successGenerateButton');const oldText=btn?btn.textContent:'';if(btn){btn.disabled=true;btn.textContent='리포트 생성 중...'}try{const results=Array.isArray(state.successResults)&&state.successQuery===query?state.successResults:await findSuccessCasesWithFallback(query,12);if(!results.length)throw new Error('검색 키워드와 일치하는 성공사례가 없습니다. 먼저 다른 키워드로 사례를 검색해주세요.');state.successResults=results;state.successQuery=query;state.successInsight=val('successInsight');const selectedIds=collectSelectedSuccessCaseIds();if(!selectedIds.length)throw new Error(successUi('needSelect','Select at least one success case.'));if(selectedIds.length>SUCCESS_MAX_SELECTED_CASES)throw new Error(successMaxSelectMessage());const selectedResults=results.filter((item,index)=>selectedIds.includes(successResultKey(item,index))).slice(0,SUCCESS_MAX_SELECTED_CASES);if(!selectedResults.length)throw new Error(successUi('missingSelected','Selected cases are not in current results.'));state.selectedSuccessCaseIds=selectedResults.map((item,index)=>successResultKey(item,index));state.selectedSuccessCaseId=state.selectedSuccessCaseIds[0]||null;const title=`${p.name} ${successUi('reportTitle','Success Case Reemployment Analysis')} (${query}, ${selectedResults.length}${successUi('selectedCount',' selected')})`;const generated=await generateGeminiSuccessCaseReport(query,selectedResults,p,state.successInsight);const html=withReportBrand(generated.html,title);state.currentReport={id:null,type:'success',title,participantId:p.id,participantName:p.name,html,createdAt:today()};state.editMode=false;render();toast('성공사례 리포트가 생성되었습니다.');return{tokenUsage:generated.tokenUsage}}catch(err){console.error('성공사례 Gemini 리포트 생성 실패',err);throw err}finally{if(btn&&document.body.contains(btn)){btn.disabled=false;btn.textContent=oldText||successUi('generate','Generate counselor report')}}}

function isSuccessJsonParseError(err){return['JSON_PARSE_ERROR','JSON_REPAIR_FAILED','TRUNCATED_JSON'].includes(err?.errorType)||err instanceof SyntaxError||String(err?.message||'').includes('JSON')}
function buildSuccessGeminiRequest(keyword,matchedCases,participant,insight,useSearch=true){return{modelName:getGeminiModel('success'),request:({modelName})=>window.AI_GATEWAY.generateReportContent({model:modelName,reportType:'success',keyword,matchedCases,participant,insight,useSearch,request:fetchGeminiWithRetry}),schema:SUCCESS_ANALYSIS_SCHEMA_FOR_REPAIR,context:'성공사례 리포트'}}
async function requestGeminiSuccessAnalysisRecovered(keyword,matchedCases,participant,insight,useSearch=true,options={}){const requestData=buildSuccessGeminiRequest(keyword,matchedCases,participant,insight,useSearch);const result=await generateJsonWithRecovery({reportType:'success',modelScope:'success',...requestData,allowJsonRepair:options.allowJsonRepair!==false});return{analysis:result.json,tokenUsage:result.tokenUsage}}
async function requestGeminiSuccessAnalysisWithSearchFallback(keyword,matchedCases,participant,insight,options={}){if(SUCCESS_USE_GOOGLE_SEARCH){try{return await requestGeminiSuccessAnalysisRecovered(keyword,matchedCases,participant,insight,true,options)}catch(searchErr){if(searchErr?.isGeminiRateLimit||isSuccessJsonParseError(searchErr))throw searchErr;console.warn('Gemini Google Search 호출 실패, 검색 도구 없이 재시도합니다.',searchErr);return requestGeminiSuccessAnalysisRecovered(keyword,matchedCases,participant,insight,false,options)}}return requestGeminiSuccessAnalysisRecovered(keyword,matchedCases,participant,insight,false,options)}
async function generateGeminiSuccessCaseReport(keyword,matchedCases,participant,insight){const result=await requestGeminiSuccessAnalysisWithSearchFallback(keyword,matchedCases,participant,insight);return{html:renderSuccessReportFromData(buildSuccessReportData(keyword,matchedCases,participant,insight,result.analysis)),tokenUsage:result.tokenUsage}}

  window.searchSuccessCases = searchSuccessCases;
  window.resetSuccessCaseSearch = resetSuccessCaseSearch;
  window.toggleSuccessCaseSelection = toggleSuccessCaseSelection;
  window.chooseSuccessCase = chooseSuccessCase;
  window.generateSuccessReportWithGemini = generateSuccessReportWithGemini;
  window.normalizeSuccessGeminiAnalysis = normalizeSuccessGeminiAnalysis;
  window.buildSuccessReportData = buildSuccessReportData;
  window.renderSuccessReportFromData = renderSuccessReportFromData;
  window.REPORT_MODULES.register('success', {
    tracksGenerationUsage: true,
    renderForm() {
      return successModuleForm();
    },
    validate() {
      const p = getParticipant();
      if (!p) return '내담자 분석 정보를 찾을 수 없습니다.';
      const query = val('successJobKeyword');
      if (!query) return successUi('needQuery', 'Search keyword is required.');
      const results = Array.isArray(state.successResults) && state.successQuery === query ? state.successResults : [];
      if (!results.length) return '검색 키워드와 일치하는 성공사례가 없습니다. 먼저 다른 키워드로 사례를 검색해주세요.';
      const selectedIds = collectSelectedSuccessCaseIds();
      if (!selectedIds.length) return successUi('needSelect', 'Select at least one success case.');
      if (selectedIds.length > SUCCESS_MAX_SELECTED_CASES) return successMaxSelectMessage();
      const selectedResults = results.filter((item, index) => selectedIds.includes(successResultKey(item, index)));
      if (!selectedResults.length) return successUi('missingSelected', 'Selected cases are not in current results.');
      return true;
    },
    async generate() {
      return window.generateSuccessReportWithGemini();
    }
  });
})();
