(function () {
const SUCCESS_USE_GOOGLE_SEARCH = false;
function normalizeSuccessGeminiAnalysis(raw={}){const arr=value=>Array.isArray(value)?value.filter(Boolean):[];const normalized={preparationAnalysis:{summary:String(raw.preparationAnalysis?.summary||''),rows:arr(raw.preparationAnalysis?.rows).map(item=>({item:item.item||'',caseCheck:item.caseCheck||'',typicalPreparation:item.typicalPreparation||'',preparationMethod:item.preparationMethod||'',typicalPeriod:item.typicalPeriod||'',counselingUse:item.counselingUse||''}))},certificatePreparationInfo:{summary:String(raw.certificatePreparationInfo?.summary||''),rows:arr(raw.certificatePreparationInfo?.rows).map(item=>({name:item.name||'',purpose:item.purpose||'',method:item.method||'',typicalPeriod:item.typicalPeriod||'',outlook:item.outlook||'',note:item.note||''}))},counselingComments:arr(raw.counselingComments).map(item=>String(item||'')).filter(Boolean),counselingQuestions:arr(raw.counselingQuestions).map(item=>String(item||'')).filter(Boolean)};const missing=[];if(!normalized.preparationAnalysis.summary||!normalized.preparationAnalysis.rows.length)missing.push('준비 및 기간 분석');if(!normalized.certificatePreparationInfo.summary||!normalized.certificatePreparationInfo.rows.length)missing.push('자격증·준비 정보');if(!normalized.counselingComments.length)missing.push('상담 코멘트');if(!normalized.counselingQuestions.length)missing.push('상담에 활용할 질문');if(missing.length)throw new Error(`Gemini 응답 필수 항목 누락: ${missing.join(', ')}`);return normalized}
function buildSuccessReportData(keyword,matchedCases,participant,insight='',geminiRaw){const items=(matchedCases||[]).filter(Boolean);const rows=items.map(item=>item.case||item).filter(Boolean);if(!rows.length)throw new Error('선택된 성공사례 데이터가 없습니다.');const gemini=normalizeSuccessGeminiAnalysis(geminiRaw);const data={keyword,participant,items,rows,generatedAt:new Date().toLocaleString('ko-KR'),keywords:successCommonKeywords(items),prepAnalysis:gemini.preparationAnalysis,certificateInfo:gemini.certificatePreparationInfo,counselingComments:gemini.counselingComments,counselingQuestions:gemini.counselingQuestions};const caseNames={};rows.forEach(row=>{const id=successCaseId(row);if(id)caseNames[id]=row[successFieldKey(0)]||''});const clean=value=>{if(typeof value==='string')return value.replace(/CASE-\d{4}/g,id=>caseNames[id]||'').replace(/\s{2,}/g,' ').trim();if(Array.isArray(value))return value.map(clean);if(value&&typeof value==='object'){Object.keys(value).forEach(key=>{value[key]=clean(value[key])})}return value};return clean(data)}
function renderSuccessReportFromData(data){const esc=escapeHtml;const prepRows=data.prepAnalysis.rows;const certRows=data.certificateInfo.rows;return `<div class="success-report"><section class="success-section"><div class="success-section-head"><h2>${successUi('topCases','Representative success cases')}</h2><p>${successUi('topCasesDesc','Top matched cases from SUCCESS_CASE_DB.')}</p></div>${successCaseSummaryHtml(data.items.slice(0,5))}</section><section class="success-section"><div class="success-section-head"><h2>${successUi('prepAnalysis','Preparation and duration analysis')}</h2><p>${successUi('prepDesc','Checklist from casebook preparation fields.')}</p></div><div class="success-highlight">${esc(data.prepAnalysis.summary)}</div><table class="success-cert-table"><thead><tr><th>${successUi('tableItem','Item')}</th><th>${successUi('tableCaseCheck','Casebook check')}</th><th>통상 준비 내용</th><th>준비 방법</th><th>통상 준비기간</th><th>${successUi('tableCounselUse','Counseling use')}</th></tr></thead><tbody>${prepRows.map(item=>`<tr><td>${esc(item.item||'-')}</td><td>${esc(item.caseCheck||'-')}</td><td>${esc(item.typicalPreparation||'-')}</td><td>${esc(item.preparationMethod||'-')}</td><td>${esc(item.typicalPeriod||'-')}</td><td>${esc(item.counselingUse||'-')}</td></tr>`).join('')}</tbody></table></section><section class="success-section"><div class="success-section-head"><h2>${successUi('certInfo','Certificate / preparation info')}</h2><p>${successUi('certFallbackDesc','Fallback guidance area.')}</p></div><div class="success-highlight">${esc(data.certificateInfo.summary)}</div><table class="success-cert-table"><thead><tr><th>${successUi('certName','Name')}</th><th>직무 연결 이유</th><th>${successUi('certMethod','Method')}</th><th>${successUi('certPeriod','Period')}</th><th>${successUi('certOutlook','Salary / outlook')}</th><th>확인 사항</th></tr></thead><tbody>${certRows.map(item=>`<tr><td>${esc(item.name||'-')}</td><td>${esc(item.purpose||'-')}</td><td>${esc(item.method||'-')}</td><td>${esc(item.typicalPeriod||'-')}</td><td>${esc(item.outlook||'-')}</td><td>${esc(item.note||'-')}</td></tr>`).join('')}</tbody></table></section><section class="success-section"><div class="success-section-head"><h2>${successUi('advice','Counseling comments')}</h2><p></p></div><div class="success-advice-box">${data.counselingComments.slice(0,6).map(text=>`<p>${esc(text).replaceAll('\n','<br>')}</p>`).join('')}</div></section><section class="success-section"><div class="success-section-head"><h2>${successUi('memo','Counseling questions')}</h2><p></p></div><div class="success-highlight"><strong>${successUi('keywords','Keywords')}:</strong> ${esc(data.keywords.join(', ')||'-')}</div><ul class="success-question-list">${data.counselingQuestions.slice(0,6).map(text=>`<li>${esc(text)}</li>`).join('')}</ul></section></div>`}

function normalizeSuccessText(text){return String(text||'').toLowerCase().replace(/[()[\]{}·ㆍ,./\\|:;'"‘’“”\-+_]/g,' ').replace(/\s+/g,' ').trim()}
function compactSuccessText(text){return normalizeSuccessText(text).replace(/\s+/g,'')}
function successTokens(text){return normalizeSuccessText(text).split(' ').filter(t=>t.length>=2)}
function addSuccessTerm(terms,term){const value=normalizeSuccessText(term);if(value)terms.add(value);const compact=compactSuccessText(term);if(compact&&compact!==value)terms.add(compact)}
function successUi(key,fallback=''){const assist=successSearchAssist();return assist.ui&&assist.ui[key]?assist.ui[key]:fallback}
function getSuccessQueryTerms(query){const terms=new Set();successTokens(query).forEach(t=>addSuccessTerm(terms,t));addSuccessTerm(terms,query);Object.entries(successRelatedKeywordMap()).forEach(([base,aliases])=>{const safeAliases=Array.isArray(aliases)?aliases:[];const needles=[normalizeSuccessText(base),...safeAliases.map(normalizeSuccessText)].filter(Boolean);const compactNeedles=[compactSuccessText(base),...safeAliases.map(compactSuccessText)].filter(Boolean);const queryCompact=compactSuccessText(query);const matched=compactNeedles.some(v=>queryCompact.includes(v)||v.includes(queryCompact))||successTokens(query).some(token=>needles.some(v=>v.includes(token)||token.includes(v)));if(matched){addSuccessTerm(terms,base);safeAliases.forEach(a=>addSuccessTerm(terms,a))}});return [...terms].filter(t=>t.length>=2)}
function successSearchAssist(){return typeof SUCCESS_CASE_SEARCH_ASSIST==='object'&&SUCCESS_CASE_SEARCH_ASSIST?SUCCESS_CASE_SEARCH_ASSIST:{}}
function successSearchFields(){const assist=successSearchAssist();if(Array.isArray(assist.searchFields)&&assist.searchFields.length)return assist.searchFields;if(typeof SUCCESS_SEARCH_FIELDS==='object'&&Array.isArray(SUCCESS_SEARCH_FIELDS))return SUCCESS_SEARCH_FIELDS;return []}
function successFieldKey(i){return (successSearchFields()[i]||{}).key||''}
function successRelatedKeywordMap(){const legacy=typeof SUCCESS_SIMILAR_KEYWORDS==='object'&&SUCCESS_SIMILAR_KEYWORDS?SUCCESS_SIMILAR_KEYWORDS:{};const assist=successSearchAssist();return {...legacy,...(assist.relatedKeywords||{})}}
function successCaseId(row){return row&&(row[Object.keys(row).find(k=>/ID/i.test(k))]||'')}
function successExtraValue(row,idx){const keys=Object.keys(row||{});return row[keys[idx]]||''}
function successSourceText(row){const field=successUi('sourceField','');return (field&&row&&row[field])||successExtraValue(row,18)||''}
function successFieldScore(value,terms,weight){const text=normalizeSuccessText(value);const compact=compactSuccessText(value);if(!text)return {score:0,terms:[]};let score=0;const matched=[];terms.forEach(term=>{const norm=normalizeSuccessText(term);const c=compactSuccessText(term);if(!norm||!c)return;if(text.includes(norm)||compact.includes(c)){score+=weight;matched.push(term)}else if(norm.length>=3&&text.split(/[\s,./()]+/).some(token=>token&&token.includes(norm))){score+=Math.max(1,Math.floor(weight/2));matched.push(term)}});return {score,terms:matched}}
function successScoreCase(row,query){const terms=getSuccessQueryTerms(query);if(!terms.length)return {score:0,matchedTerms:[],matchedFields:[]};let score=0;const matchedTerms=new Set();const matchedFields=[];successSearchFields().forEach(field=>{const result=successFieldScore(row[field.key],terms,field.weight||1);if(result.score){score+=result.score;matchedFields.push(field.key);result.terms.forEach(t=>matchedTerms.add(t))}});const cq=compactSuccessText(query);const current=compactSuccessText(row[successFieldKey(0)]);if(cq&&current){if(cq===current)score+=30;else if(current.includes(cq)||cq.includes(current))score+=18}const keyword=compactSuccessText(row[successFieldKey(7)]);if(cq&&keyword.includes(cq))score+=12;return {score:Math.min(100,Math.round(score)),matchedTerms:[...matchedTerms],matchedFields:[...new Set(matchedFields)]}}
function findSuccessCases(query,limit=12){return SUCCESS_CASE_DB.map(row=>{const result=successScoreCase(row,query);return {case:row,score:result.score,matchedTerms:result.matchedTerms||[],matchedFields:result.matchedFields||[]}}).filter(x=>x.score>=3).sort((a,b)=>b.score-a.score||String(a.case[successFieldKey(0)]).localeCompare(String(b.case[successFieldKey(0)]),'ko')).slice(0,limit)}
function successSelectedCaseIds(){if(Array.isArray(state.selectedSuccessCaseIds))return state.selectedSuccessCaseIds;return state.selectedSuccessCaseId?[state.selectedSuccessCaseId]:[]}
function collectSelectedSuccessCaseIds(){const checked=[...document.querySelectorAll('input[name="successCaseSelect"]:checked')].map(el=>el.value).filter(Boolean);return checked.length||document.getElementById('successCaseResults')?checked:successSelectedCaseIds()}
function toggleSuccessCaseSelection(id,checked){const ids=new Set(successSelectedCaseIds());if(checked)ids.add(id);else ids.delete(id);state.selectedSuccessCaseIds=[...ids];state.selectedSuccessCaseId=state.selectedSuccessCaseIds[0]||null;const hidden=document.getElementById('successSelectedCaseId');if(hidden)hidden.value=state.selectedSuccessCaseIds.join(',')}
function searchSuccessCases(){const query=val('successJobKeyword');if(!query){toast(successUi('needQuery','Search keyword is required.'));return}const results=findSuccessCases(query,12);state.successQuery=query;state.successResults=results;state.selectedSuccessCaseIds=results[0]?[successCaseId(results[0].case)]:[];state.selectedSuccessCaseId=state.selectedSuccessCaseIds[0]||null;state.successInsight=val('successInsight');render();toast(results.length?`${results.length} matched cases found.`:'No matched cases found.')}
function chooseSuccessCase(id){toggleSuccessCaseSelection(id,!successSelectedCaseIds().includes(id));render()}
function resetSuccessCaseSearch(){state.successQuery='';state.successResults=[];state.selectedSuccessCaseId=null;state.selectedSuccessCaseIds=[];state.successInsight='';render()}
function successCaseResultHtml(){const results=state.successResults||[];const selectedIds=successSelectedCaseIds();if(!results.length)return `<div class="empty">${successUi('emptySearch','Search success cases.')}<br>${successUi('emptySearchSub','Matched cases will appear here.')}</div>`;return `<div class="notice">${successUi('selectionNotice','Select at least one success case. No limit.')}</div><div class="success-search-results">${results.map((item,i)=>{const row=item.case;const id=successCaseId(row);const selected=selectedIds.includes(id);return `<label class="success-result-card ${selected?'selected':''}"><input type="checkbox" name="successCaseSelect" value="${escapeHtml(id)}" ${selected?'checked':''} onchange="toggleSuccessCaseSelection('${escapeHtml(id)}',this.checked)"><span class="success-result-rank">TOP ${i+1}</span><strong>${escapeHtml(row[successFieldKey(0)])}</strong><span>${escapeHtml(row[successFieldKey(1)])}</span><small>${escapeHtml(item.score)} pt - ${escapeHtml((item.matchedFields||[]).join(', ')||'DB')}</small><small>${successUi('sourceLabel','Source')}: ${escapeHtml(successSourceText(row)||'-')}</small></label>`}).join('')}</div>`}
function successFieldRows(row,keys){return keys.map(key=>`<p><strong>${escapeHtml(key)}:</strong> ${escapeHtml(row[key]||'-')}</p>`).join('')}
function successRecommendedPrep(items){const rows=(items||[]).map(item=>item.case||item);const prep=[];if(rows.some(row=>String(row[successFieldKey(2)]||'').trim()))prep.push(successUi('prepCert','Review certificates and licenses found in the casebook.'));if(rows.some(row=>String(row[successFieldKey(3)]||'').trim()))prep.push(successUi('prepProgram','Use public employment, training, and transition support programs as execution steps.'));if(rows.some(row=>String(row[successFieldKey(4)]||'').trim()))prep.push(successUi('prepField','Translate prior management and field activity into job-ready resume language.'));if(!prep.length)prep.push(successUi('prepDefault','Split preparation into certificate, training, field practice, and public support tasks.'));return prep.slice(0,5)}
function successCommonKeywords(items){const counts={};(items||[]).forEach(item=>String((item.case||item)[successFieldKey(7)]||'').split(',').map(v=>v.trim()).filter(Boolean).forEach(v=>{counts[v]=(counts[v]||0)+1}));return Object.entries(counts).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0],'ko')).map(x=>x[0]).slice(0,8)}
function successCaseSummaryHtml(items){return `<div class="success-case-grid">${(items||[]).slice(0,5).map((item,i)=>successCaseCardHtml(item.case||item,item.score||0,i)).join('')}</div>`}
function successSplitValues(value){return String(value||'').split(/[,\/]| and | or |\n/).map(v=>v.replace(/["'()]/g,'').trim()).filter(Boolean)}
function successCountEntries(rows,key){const counts={};rows.forEach(row=>successSplitValues(row[key]).forEach(v=>{counts[v]=(counts[v]||0)+1}));return Object.entries(counts).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0],'ko'))}
function successTopText(rows,key,empty='-'){const entries=successCountEntries(rows,key);return entries.length?entries.slice(0,3).map(([name,count])=>`${name} (${count})`).join(', '):empty}
function successPrepFlags(rows){return [{label:successUi('flagCert','Certificate preparation'),value:rows.some(row=>String(row[successFieldKey(2)]||'').trim())?successUi('confirmed','Confirmed'):successUi('caseCheck','Check by case')},{label:successUi('flagEdu','Training participation'),value:rows.some(row=>String(row[successFieldKey(3)]||'').trim())?successUi('confirmed','Confirmed'):successUi('caseCheck','Check by case')},{label:successUi('flagPractice','Practical supplement'),value:rows.some(row=>String(row[successFieldKey(4)]||'').trim())?successUi('confirmed','Confirmed'):successUi('caseCheck','Check by case')},{label:successUi('flagResume','Resume/interview'),value:successUi('counselCheck','Check in counseling')}]}
function successDurationSummary(rows){return successUi('durationNote','Many cases do not specify preparation duration, so compare preparation items first.')}
function successCertGuideRows(keyword,rows){const guide=successSearchAssist().certInfo||{};const queryTerms=getSuccessQueryTerms(keyword).map(compactSuccessText);const fromGuide=Object.entries(guide).filter(([key])=>queryTerms.some(t=>compactSuccessText(key).includes(t)||t.includes(compactSuccessText(key)))).flatMap(([,items])=>items);const dbCerts=successCountEntries(rows,successFieldKey(2)).slice(0,4).map(([name])=>({name,difficulty:successUi('casebook','Casebook'),method:successUi('dbCertMethod','Found in SUCCESS_CASE_DB certificate/training field'),path:successUi('dbCertPath','Compare with job posting requirements and check training schedules'),period:successUi('varies','Varies'),salary:successUi('variesByJob','Varies by job'),outlook:successUi('expandable','Expandable to related jobs')}));const seen=new Set();return [...fromGuide,...dbCerts].filter(item=>{const key=compactSuccessText(item.name);if(!key||seen.has(key))return false;seen.add(key);return true}).slice(0,6)}
function successPatternSentences(rows){const transitions=successCountEntries(rows,successFieldKey(5)).slice(0,3);const jobs=successCountEntries(rows,successFieldKey(0)).slice(0,3);const prep=successRecommendedPrep(rows);const sentences=[];if(transitions.length)sentences.push(`${transitions.map(([n,c])=>`${n} ${c}`).join(', ')}`);if(jobs.length)sentences.push(`${successUi('linkedJobs','Linked jobs')}: ${jobs.map(([n])=>n).join(', ')}`);if(prep.length)sentences.push(prep[0]);return sentences}
function successCounselingComments(rows,keyword,insight){const jobs=successTopText(rows,successFieldKey(0),'-');const prep=successTopText(rows,successFieldKey(3),'-');const comments=[`${successUi('commentJobs','Matched jobs')}: ${jobs}`,`${successUi('commentPrep','Preparation pattern')}: ${prep}`,successUi('commentBridge','Bridge prior career assets with new job requirements before focusing only on certificates.')];if(insight)comments.unshift(insight);return comments.slice(0,5)}
function successCaseCardHtml(row,score,index){return `<article class="success-case-card"><div class="success-card-top"><span class="success-rank">TOP ${index+1}</span><span class="success-score">${escapeHtml(score)} pt</span></div><h3>${escapeHtml(row[successFieldKey(0)])}</h3><p class="small"><strong>${successUi('sourceLabel','Source')}:</strong> ${escapeHtml(successSourceText(row)||'-')}</p><div class="success-timeline"><div><b>${successUi('previousCareer','Previous career')}</b><span>${escapeHtml(row[successFieldKey(1)]||'-')}</span></div><div><b>${successUi('preparation','Preparation')}</b><span>${escapeHtml(row[successFieldKey(3)]||'-')}</span></div><div><b>${successUi('currentJob','Current job')}</b><span>${escapeHtml(row[successFieldKey(0)]||'-')}</span></div></div><dl class="success-mini-list"><dt>${successUi('certTraining','Certificate/training')}</dt><dd>${escapeHtml(row[successFieldKey(2)]||'-')}</dd><dt>${successUi('activities','Activities')}</dt><dd>${escapeHtml(row[successFieldKey(4)]||'-')}</dd><dt>${successUi('counselSentence','Counseling sentence')}</dt><dd>${escapeHtml(successExtraValue(row,14)||successUi('sentenceDefault','Use this case as a reference for career asset translation.'))}</dd></dl></article>`}
function successModuleForm(){const p=getParticipant();if(!p)return `<div class="empty">참여자를 먼저 등록해야 리포트를 생성할 수 있습니다.</div>`;return `<div class="job-api-box"><strong>${successUi('formIntroTitle','Public casebook success analysis')}</strong><br>${successUi('formIntroDesc','Searches SUCCESS_CASE_DB and builds a counselor report.')}</div><div class="field"><label>Gemini API 키 *</label><input id="successApiKey" type="password" value="${escapeHtml(localStorage.getItem('GEMINI_API_KEY')||'')}" placeholder="필수 입력: Gemini 분석 결과로만 리포트를 생성합니다."></div><div class="field"><label>${successUi('jobLabel','Job keyword *')}</label><input id="successJobKeyword" value="${escapeHtml(state.successQuery||p.target||'')}" placeholder="${successUi('jobPlaceholder','ex: safety, counseling, welfare')}" onkeydown="if(event.key==='Enter'){event.preventDefault();searchSuccessCases()}"></div><input type="hidden" id="successSelectedCaseId" value="${escapeHtml(state.selectedSuccessCaseId||'')}"><div class="actions"><button class="btn full" onclick="searchSuccessCases()">${successUi('search','Search cases')}</button><button class="btn secondary full" onclick="resetSuccessCaseSearch()">${successUi('reset','Reset')}</button></div><div id="successCaseResults" style="margin-top:14px">${successCaseResultHtml()}</div><div class="field"><label>${successUi('insightLabel','Counselor insight')}</label><textarea id="successInsight" placeholder="${successUi('insightPlaceholder','Write participant context.')}">${escapeHtml(state.successInsight||'')}</textarea></div><button id="successGenerateButton" class="btn full" onclick="generateSuccessReportWithGemini()">${successUi('generate','Generate counselor report')}</button>`}
function successGeminiPrompt(keyword,matchedCases,participant,insight){if(!window.SUCCESS_PROMPTS?.user)throw new Error('성공사례 프롬프트 파일(successPrompt.js)을 찾지 못했습니다.');return window.SUCCESS_PROMPTS.user({keyword,participant,counselorInsight:insight||'',selectedCases:(matchedCases||[]).map(item=>item.case||item)})}
function successGeminiError(err){const status=err?.status?'HTTP '+err.status+': ':'';const message=String(err?.apiMessage||err?.message||'알 수 없는 오류');if(err?.isGeminiRateLimit)return GEMINI_RATE_LIMIT_ERROR_MESSAGE;if(err?.isGeminiTemporaryFailure)return 'Gemini API 일시 장애: '+message;if(err?.isNetworkError||err instanceof TypeError)return 'Gemini API 네트워크 오류: '+message;return status?'Gemini API 오류: '+status+message:message}
async function requestGeminiSuccessAnalysis(apiKey,keyword,matchedCases,participant,insight,useSearch=true){const model=getGeminiModel('success');if(!window.SUCCESS_PROMPTS?.system)throw new Error('성공사례 프롬프트 파일(successPrompt.js)을 찾지 못했습니다.');const generationConfig={temperature:.2,topP:.8};if(!useSearch)generationConfig.responseMimeType='application/json';const body={system_instruction:{parts:[{text:window.SUCCESS_PROMPTS.system()}]},contents:[{role:'user',parts:[{text:successGeminiPrompt(keyword,matchedCases,participant,insight)}]}],generationConfig};if(useSearch)body.tools=[{google_search:{}}];const res=await window.AI_GATEWAY.generateContent({apiKey,model,body,request:fetchGeminiWithRetry});const data=await res.json().catch(()=>({}));if(!res.ok){const err=new Error(data?.error?.message||`Gemini API 요청 실패 (${res.status} ${res.statusText})`);err.status=res.status;throw err}const candidate=data?.candidates?.[0]||{};if(candidate.finishReason&&candidate.finishReason!=='STOP')throw new Error(`Gemini 응답이 완료되지 않았습니다. 종료 사유: ${candidate.finishReason}`);const text=(candidate?.content?.parts||[]).map(part=>part.text||'').join('\n').trim();if(!text)throw new Error('Gemini 응답에서 성공사례 분석 JSON을 찾지 못했습니다.');try{return{analysis:parseGeminiJson(text),tokenUsage:normalizeTokenUsage(data.usageMetadata)}}catch(err){throw new Error(`Gemini 응답 JSON 해석 실패: ${err.message||'형식이 올바르지 않습니다.'}`)}}
async function generateGeminiSuccessCaseReport(apiKey,keyword,matchedCases,participant,insight){if(!apiKey)throw new Error('Gemini API 키를 입력해주세요.');localStorage.setItem('GEMINI_API_KEY',apiKey);let result;if(SUCCESS_USE_GOOGLE_SEARCH){try{result=await requestGeminiSuccessAnalysis(apiKey,keyword,matchedCases,participant,insight,true)}catch(searchErr){if(searchErr?.isGeminiRateLimit)throw searchErr;console.warn('Gemini Google Search 호출 실패, 검색 도구 없이 재시도합니다.',searchErr);result=await requestGeminiSuccessAnalysis(apiKey,keyword,matchedCases,participant,insight,false)}}else{result=await requestGeminiSuccessAnalysis(apiKey,keyword,matchedCases,participant,insight,false)}return{html:renderSuccessReportFromData(buildSuccessReportData(keyword,matchedCases,participant,insight,result.analysis)),tokenUsage:result.tokenUsage}}
async function generateSuccessReportWithGemini(){const p=getParticipant();if(!p){toast('내담자 분석 정보를 찾을 수 없습니다.');return}const query=val('successJobKeyword');if(!query){toast(successUi('needQuery','Search keyword is required.'));return}const apiKey=val('successApiKey');if(!apiKey){toast('Gemini API 키를 입력해주세요. 성공사례 리포트는 Gemini 분석 결과로만 생성됩니다.');return}const btn=document.getElementById('successGenerateButton');const oldText=btn?btn.textContent:'';if(btn){btn.disabled=true;btn.textContent='리포트 생성 중...'}try{const results=Array.isArray(state.successResults)&&state.successQuery===query?state.successResults:findSuccessCases(query,12);if(!results.length)throw new Error('검색 키워드와 일치하는 성공사례가 없습니다. 먼저 다른 키워드로 사례를 검색해주세요.');state.successResults=results;state.successQuery=query;state.successInsight=val('successInsight');const selectedIds=collectSelectedSuccessCaseIds();if(!selectedIds.length)throw new Error(successUi('needSelect','Select at least one success case.'));const selectedResults=results.filter(item=>selectedIds.includes(successCaseId(item.case)));if(!selectedResults.length)throw new Error(successUi('missingSelected','Selected cases are not in current results.'));state.selectedSuccessCaseIds=selectedResults.map(item=>successCaseId(item.case));state.selectedSuccessCaseId=state.selectedSuccessCaseIds[0]||null;const title=`${p.name} ${successUi('reportTitle','Success Case Reemployment Analysis')} (${query}, ${selectedResults.length}${successUi('selectedCount',' selected')})`;const generated=await generateGeminiSuccessCaseReport(apiKey,query,selectedResults,p,state.successInsight);const html=withReportBrand(generated.html,title);state.currentReport={id:null,type:'success',title,participantId:p.id,participantName:p.name,html,createdAt:today()};state.editMode=false;render();toast('Gemini 성공사례 리포트가 생성되었습니다.');return{tokenUsage:generated.tokenUsage}}catch(err){console.error('성공사례 Gemini 리포트 생성 실패',err);throw err}finally{if(btn&&document.body.contains(btn)){btn.disabled=false;btn.textContent=oldText||successUi('generate','Generate counselor report')}}}

  window.searchSuccessCases = searchSuccessCases;
  window.resetSuccessCaseSearch = resetSuccessCaseSearch;
  window.toggleSuccessCaseSelection = toggleSuccessCaseSelection;
  window.chooseSuccessCase = chooseSuccessCase;
  window.generateSuccessReportWithGemini = generateSuccessReportWithGemini;
  window.normalizeSuccessGeminiAnalysis = normalizeSuccessGeminiAnalysis;
  window.buildSuccessReportData = buildSuccessReportData;
  window.renderSuccessReportFromData = renderSuccessReportFromData;
  window.REPORT_MODULES.register('success', {
    tracksGenerationUsage: true,
    renderForm() {
      return successModuleForm();
    },
    async generate() {
      return window.generateSuccessReportWithGemini();
    }
  });
})();
